---

- name: Copy backend
  template:
    src: "files/artifact.tar.gz"
    dest: "~/"

- name: extract backend
  ansible.builtin.unarchive:
    src: ~/artifact.tar.gz
    dest: ~/

- name: "Excute node app with pm2"
  shell: |
    cd backend/
    npm install
    pm2 stop default
    pm2 start npm -- start